### ISSUE TITLE
Please set source_code_uri for the gem

### ISSUE THREAD

**Issue by amatsuda** [fog/fog-rackspace#16]
Could anyone with the gem push authority please set the source_code_uri for this gem as `https://github.com/fog/fog-rackspace` just like you're doing so for https://rubygems.org/api/v1/gems/fog-terremark.json?

It should be able to be done via https://rubygems.org/gems/fog-rackspace => Edit

**Comment by plribeiro3000** [comment]
Done. Thanks for noting!

**Comment by amatsuda** [comment]
@plribeiro3000 Thank you for your quick work!!

**Comment by plribeiro3000** [comment]
👍
