### ISSUE TITLE
 Search for support-sdk@racksapce.com and remove

### ISSUE THREAD

**Issue by catlook** [fog/fog-rackspace#24]
any found

**Comment by plribeiro3000** [comment]
@catlook ?

can you explain what did you want to do?

**Comment by catlook** [comment]
Thanks, for checking with me, Paulo.  I’d planned to do it myself, but here’s the scoop.

I found this git repo by click on the Ruby/Fog SDK documentation link on the Rackspace Developer site (https://developer.rackspace.com/docs/#sdks).  I want to make sure that the email sdk-support@rackspace.com<mailto:sdk-support@rackspace.com> doesn’t occur in the documentation anywhere, since that email is no longer monitored.   I planned to clone and search the site and submit PRs if I found any.  Is that ok?  Or is it just not necessary in this case?


-- Cat Lookabaugh, Sr. Information Developer
Rackspace Hosting – the #1 Managed Cloud Company
Info Dev Team      cat.lookabaugh@rackspace.com
Office: (210) 312-8193   Cell: (210) 364-1060

**Comment by plribeiro3000** [comment]
Thats ok. Feel free to submit a PR removing it. =)

**Comment by catlook** [comment]
Roger..if there are any.  Otherwise, I’ll close the issue.  Feel free to assign me!

-- Cat Lookabaugh, Sr. Information Developer
Rackspace Hosting – the #1 Managed Cloud Company
Info Dev Team      cat.lookabaugh@rackspace.com
Office: (210) 312-8193   Cell: (210) 364-1060

**Comment by catlook** [comment]
confirmed email not present in repo.
