### ISSUE TITLE
[fog][DEPRECATION] Unable to load Fog::Rackspace::CDN

### ISSUE THREAD

**Issue by codeodor** [fog/fog-rackspace#30]
I just did a `bundle update` in updating rails and I'm getting this error when running my tests:

`[fog][DEPRECATION] Unable to load Fog::Rackspace::CDN`
`[fog][DEPRECATION] The format Fog::CDN::Rackspace is deprecated`

The trouble is twofold: 

1) I don't actually use the code `Fog::Rackspace::CDN` in my app
2) it doesn't tell me where it is failing, so I am not even sure where to look among my gems.

Any ideas on how to go about fixing this?

**Comment by apple4ever** [comment]
I am getting the same thing. Looks like it works, but the message is annoying, and at some point I'm assuming it will stop working.

**Comment by apple4ever** [comment]
Actually seems like its similar to #29

**Comment by codeodor** [comment]
I'll close in favor of that one then.
